#!/bin/bash
#SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END
#SBATCH --mail-user=lhtran
#SBATCH -p gpu
#SBATCH --gres=gpu:a4000:1
#SBATCH -t 3:00:00
#SBATCH -c 1
#SBATCH -a 1-1
#SBATCH --mem=16g
#SBATCH -o /home/lhtran/class/cheme_577/challenge_4/unrelated/logs/out.%a
#SBATCH -e /home/lhtran/class/cheme_577/challenge_4/unrelated/logs/out.%a

GROUP_SIZE=1

#source activate /software/conda/envs/tensorflow
#source activate mlfold
source activate SE3-nvidia

for I in $(seq 1 $GROUP_SIZE)
do
    J=$(($SLURM_ARRAY_TASK_ID * $GROUP_SIZE + $I - $GROUP_SIZE))
    CMD=$(sed -n "${J}p" /home/lhtran/class/cheme_577/challenge_4/unrelated/cmds )
    echo "${CMD}" | bash
done
